### ISSUE TITLE
Broken with Doorkeeper 5.6.5

### ISSUE THREAD

**Issue by dbussink** [exop-group/doorkeeper-device_authorization_grant#10]
Doorkeeper 5.6.5 includes https://github.com/doorkeeper-gem/doorkeeper/pull/1602 which breaks this gem since the signature of `find_or_create_access_token` is changed for the custom attributes as discussed in that PR. 

I guess Doorkeeper didn't consider this internal change to need a new version, so it looks like this gem might be using internals of Doorkeeper that it shouldn't? Is there a good way to fix this?

**Comment by irminsul** [comment]
Thanks for reporting this, I'll have a look!

**Comment by irminsul** [comment]
Fixed with v1.0.2
